services:
  postgres:
    image: postgres:16
    container_name: balance_ledger_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB is required}
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is required}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:?POSTGRES_PASS is required}
    ports:
      - "5432:5432"
    volumes:
      - balance_ledger_postgres_data:/var/lib/postgresql/data

volumes:
  balance_ledger_postgres_data: